version: '3.3'
services:
  proxy:
    build: ./proxy
    image: lucj/kernelci-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
  frontend:
    build: ./frontend
    image: lucj/kernelci-frontend
    depends_on:
      - redis
    environment:
      - BACKEND_URL="http://proxy:8081/"
      - BACKEND_TOKEN="API_TOKEN"
      - SECRET_KEY="random_string"
      - DATE_RANGE=14
      - CACHE_TYPE="redis"
      - CACHE_REDIS_HOST="redis"
    restart: always
  backend:
    build: ./backend/app
    image: lucj/kernelci-backend
    depends_on:
      - mongo
      - redis
      - celery
    restart: always
  celery:
    build: ./backend/celery
    image: lucj/kernelci-celery
    restart: always
  redis:
    image: redis:3.2
    restart: always
  mongo:
    image: mongo:3.4
    restart: always
