version: '3.4'
services:
  proxy:
    image: lucj/kernelci-proxy:${TAG:-latest}
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - kci:/usr/share/nginx/html/kernelci/logs
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    image: lucj/kernelci-frontend:${TAG:-latest}
    deploy:
      restart_policy:
        condition: on-failure
  backend:
    image: lucj/kernelci-backend:${TAG:-latest}
    volumes:
      - kci:/var/www/images/kernel-ci
    deploy:
      restart_policy:
        condition: on-failure
  celery:
    image: lucj/kernelci-celery:${TAG:-latest}
    volumes:
      - kci:/var/www/images/kernel-ci
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:3.2
    deploy:
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo:3.4
    volumes:
      - data:/data/db
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  data:
  kci:
