version: '3.3'
services:
  proxy:
    build: ./proxy
    image: lucj/kernelci-proxy:${TAG:-latest}
    depends_on:
      - frontend
      - backend
    ports:
      - 8080:8080
      - 8081:8081
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    build: ./frontend
    image: lucj/kernelci-frontend:${TAG:-latest}
    depends_on:
      - backend
      - redis
    deploy:
      restart_policy:
        condition: on-failure
  backend:
    build: ./backend/app
    image: lucj/kernelci-backend:${TAG:-latest}
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
  celery:
    build: ./backend/celery
    image: lucj/kernelci-celery:${TAG:-latest}
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:3.2
    deploy:
      restart_policy:
        condition: on-failure
  mongo:
    image: mongo:3.4
    volumes:
      - data:/data/db
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  data:
